import { Badge, Button, Header, Logo, formatDate, money } from "../shared";

function UserDashboard({ data, navigate }) {
  const tenant = data.tenants.find((item) => item.id === "t1") || data.tenants[0];
  const room = data.rooms.find((item) => item.id === tenant?.roomId);
  const payments = data.payments.filter((item) => item.tenantId === tenant?.id).slice(0, 4);
  return <div className="min-h-screen bg-[#fafafa] text-[#1a1a1a]"><header className="flex items-center justify-between border-b border-[#e6e6e6] bg-white px-6 py-5 sm:px-10"><Logo /><span className="text-sm font-semibold">{tenant?.name || "Resident"}</span></header><main className="mx-auto max-w-6xl p-6 sm:p-10"><Header eyebrow="Resident portal" title={`Welcome back, ${tenant?.name?.split(" ")[0] || "Raj"}.`} description="Here is a quick view of your stay and rent." /><div className="grid gap-5 md:grid-cols-2"><section className="rounded-xl border border-[#e6e6e6] bg-white p-6"><h2 className="font-bold">Next rent payment</h2><p className="mt-5 text-3xl font-bold">{money(payments.find((p) => p.status !== "paid")?.amount || 0)}</p><p className="mt-1 text-sm text-[#575757]">Due {formatDate(payments.find((p) => p.status !== "paid")?.dueDate)}</p><Badge status="pending" /><Button variant="outline" className="mt-5" onClick={() => navigate("/auth?next=%2Fpayments")}>View payment details</Button></section><section className="rounded-xl border border-[#e6e6e6] bg-white p-6"><h2 className="font-bold">Your room</h2><p className="mt-5 text-3xl font-bold">Room {room?.id || "—"}</p><p className="mt-1 text-sm text-[#575757]">{room?.type || "Room"} · Bed {tenant?.bedId || "—"}</p><Badge status="active" /></section><section className="rounded-xl border border-[#e6e6e6] bg-white p-6 md:col-span-2"><h2 className="font-bold">Payment history</h2><div className="mt-4 divide-y divide-[#f5f5f5]">{payments.map((payment) => <div key={payment.id} className="flex justify-between py-3 text-sm"><span>{formatDate(payment.paidDate || payment.dueDate)}</span><span className="font-semibold">{money(payment.amount)} · {payment.status}</span></div>)}</div></section></div></main></div>;
}
export default UserDashboard;
